### ISSUE TITLE
Should Offramp's Request message allow for negative values

### ISSUE THREAD

**Issue by kyrsideris** [HotelsDotCom/data-highway#13] opened 2019-01-28 10:20 UTC
As it stands right now, a Request message with negative count is allowed. Please correct me if I am wrong! Example:
```json
{"type": "REQUEST", "count": -1}
```
Should we allow these count-negative requests?
  - If yes, then we should add check on the `count + requested` to be greater or equal to zero. If this check is not enforced, there might be implications related to the semantics of committed offsets.
  - If no, we should create check for `count > 0`, because count = 0 carries no meaning for a "request" message, unless if we allow it to let the client notify the server that it is still present.

**Comment by nahguam** [comment] 2019-01-28 10:40
I think we should stick closely to the intended behaviour of the reactive-streams API. Looking at the [`java.util.concurrent.Flow`](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html) API, it has this example:

```
if (n < 0) {
  IllegalArgumentException ex = new IllegalArgumentException();
  executor.execute(() -> subscriber.onError(ex));
}
```

So, for `request(0)` I think we should ignore - it's not an error, it's just a noop. `request(<0)` should throw an exception. The exception will result in the connection being closed by the service, but I'd like to introduce an `Error` event type (not just for this use case) so the service can notify the client of problems.

**Closed** 2019-01-31 15:20 UTC
Labels: enhancement
